APEXPass Class Reference
Actual APEX pass.
#include <apex.h>
Public Member Functions
bool runOnModule (Module &M) override
Running on each module.
Static Public Attributes
static char ID = 0
Registering our own pass, so it can be ran via opt.
Private Member Functions
void logPrint (const std::string &message)
Simple logging print with newline.
void logPrintDbg (const std::string &message)
Simple logging print with newline.
void logPrintUnderline (const std::string &message)
Simple logging print with newline.
void logPrintFlat (const std::string &message)
Simple logging print WITHOUT newline.
void logDumpModule (const Module &M)
Dumps whole module M.
bool functionIsProtected (const Function *F)
Returns true if function is protected, Protected functions will not be removed at the end of the APEXPass.
void findPath (const Module &M)
Finds blocks in the source function and starts exploring from these blocks using BFS.
void printPath ()
Prints path in the .
void dgInit (Module &M)
Initializes dg and calculates control & data dependencies.
void apexDgInit ()
Extracts data from and stores them into structures.
void apexDgGetBlockNodeInfo (APEXDependencyNode &apex_node, LLVMNode *node)
Stores control/reverse_control/data/reverse_data dependencies of the to the .
void apexDgPrintDependenciesCompact ()
Pretty prints , but only with data dependencies.
void apexDgFindDataDependencies (LLVMNode &node, std::vector< LLVMNode *> &dependencies, std::vector< LLVMNode *> &rev_data_dependencies)
Take and find all data dependencies that form the chain.
void apexDgGetNodeOrDie (const APEXDependencyGraph &apex_dg, const Instruction *const I, APEXDependencyNode &node)
Finds instruction in the .
void apexDgComputeFunctionDependencyBlocks (const Module &M)
We go over functions that are in and compute for each function dependencies between instructions.
void apexDgPrintFunctionDependencyBlocks ()
Pretty prints map.
void apexDgConstructBlocksFunctionsCallgraph ()
Takes that were computed by () and constructs callgraph where key is some block and value is vector of functions that this block may call.
void apexDgPrintBlocksFunctionsCallgraph ()
Pretty prints dependency blocks to functions callgraph.
void moduleParseCmdLineArgsOrDie ()
Parses command line arguments from opt.
void moduleFindTargetInstructionsOrDie (Module &M, const std::string &file, const std::string &line)
void moduleInjectExitExtract (Module &M)
Injects _apex_exit() call at the end of the .
void removeUnneededStuff (Module &M)
Figures out what DependencyBlocks and functions to remove and removes them.
void stripAllDebugSymbols (Module &M)
Strips debug symbols from every function in module .
void collectProtectedFunctions (Module &M)
Goes over all functions in the module and adds functions that are only declarations to the .
Private Attributes
std::string source_function_id_ = `main`
Source and target functions global IDs.
std::string target_function_id_ = ``
std::vector< const Instruction * > target_instructions_
Target instructions that correspond to the user input.
LLVMDependenceGraph dg_
Dependence graph: https://github.com/mchalupa/dg.
 APEXDependencyGraph apex_dg_
Holds all the necessary info about dependencies.
std::vector< DependencyBlock > path_
is the representation of computed execution path.
std::map< const Function *, std::vector< DependencyBlock > > function_dependency_blocks_
std::map< DependencyBlock, std::vector< const Function * > > blocks_functions_callgraph_
std::vector< std::string > protected_functions_
Protected functions IDs. These will not be removed by APEXPass.
Detailed Description
Actual APEX pass.
Definition at line 89 of file apex.h.
Member Function Documentation
apexDgComputeFunctionDependencyBlocks()
void APEXPass::apexDgComputeFunctionDependencyBlocks (const Module & M) [private]
We go over functions that are in and compute for each function dependencies between instructions.
Instructions that are linked via data dependencies are stored in the map.
Definition at line 485 of file apex.cpp.
References apex_dg_, apexDgFindDataDependencies(), apexDgGetNodeOrDie(), functionIsProtected(), logPrint(), and logPrintDbg().
Referenced by runOnModule().
apexDgConstructBlocksFunctionsCallgraph()
void APEXPass::apexDgConstructBlocksFunctionsCallgraph () [private]
Takes that were computed by () and constructs callgraph where key is some block and value is vector of functions that this block may call.
Definition at line 673 of file apex.cpp.
References logPrint().
Referenced by runOnModule().
apexDgFindDataDependencies()
void APEXPass::apexDgFindDataDependencies (LLVMNode & node, std::vector< LLVMNode *> & data_dependencies, std::vector< LLVMNode *> & rev_data_dependencies) [private]
Take and find all data dependencies that form the chain.
Store these dependencies in the vector.
Definition at line 377 of file apex.cpp.
References apex_dg_.
Referenced by apexDgComputeFunctionDependencyBlocks().
apexDgGetBlockNodeInfo()
void APEXPass::apexDgGetBlockNodeInfo (APEXDependencyNode & apex_node, LLVMNode * node) [private]
Stores control/reverse_control/data/reverse_data dependencies of the to the .
Definition at line 330 of file apex.cpp.
Referenced by apexDgInit().
apexDgGetNodeOrDie()
void APEXPass::apexDgGetNodeOrDie (const APEXDependencyGraph & apex_dg, const Instruction *const I, APEXDependencyNode & node) [private]
Finds instruction in the .
Returns , that is equivalent in the .
Dies if unable to find in the .
Definition at line 463 of file apex.cpp.
References logPrintFlat().
Referenced by apexDgComputeFunctionDependencyBlocks().
apexDgInit()
void APEXPass::apexDgInit () [private]
Extracts data from and stores them into structures.
Caution: () has to be called before (), dg needs to be initialized in for this to properly work, otherwise CF map will be empty.
Definition at line 278 of file apex.cpp.
References apex_dg_, apexDgGetBlockNodeInfo(), and logPrint().
Referenced by runOnModule().
collectProtectedFunctions()
void APEXPass::collectProtectedFunctions (Module & M) [private]
Goes over all functions in the module and adds functions that are only declarations to the .
We do not want to remove declarations.
Definition at line 1246 of file apex.cpp.
References logPrint(), logPrintDbg(), and protected_functions_.
Referenced by runOnModule().
findPath()
void APEXPass::findPath (const Module & M) [private]
Finds blocks in the source function and starts exploring from these blocks using BFS.
Computes path from source function to target function. Stores results in the . contains dependency blocks that are on the execution flow.
Definition at line 153 of file apex.cpp.
References logPrint(), path_, source_function_id_, and target_instructions_.
Referenced by runOnModule().
functionIsProtected()
bool APEXPass::functionIsProtected (const Function * F) [private]
Returns true if function is protected, Protected functions will not be removed at the end of the APEXPass.
Definition at line 135 of file apex.cpp.
References protected_functions_.
Referenced by apexDgComputeFunctionDependencyBlocks(), and removeUnneededStuff().
moduleInjectExitExtract()
void APEXPass::moduleInjectExitExtract (Module & M) [private]
Injects _apex_exit() call at the end of the .
Injects lib_dump_int() call before lib_exit().
Definition at line 770 of file apex.cpp.
References logPrint(), logPrintFlat(), and target_instructions_.
Referenced by runOnModule().
moduleParseCmdLineArgsOrDie()
void APEXPass::moduleParseCmdLineArgsOrDie (void) [private]
Parses command line arguments from opt.
Dies if arguments are missing or are in from format.
Definition at line 717 of file apex.cpp.
References logPrint(), logPrintDbg(), and target_instructions_.
Referenced by runOnModule().
stripAllDebugSymbols()
void APEXPass::stripAllDebugSymbols (Module & M) [private]
Strips debug symbols from every function in module .
We do this because LLVM verifier would blow up after we inserted into the module instructions without debug symbols. This way, module will be consistent.
Definition at line 1235 of file apex.cpp.
References logPrint().
Referenced by runOnModule().
Field Documentation
path_
std::vector<DependencyBlock> APEXPass::path_ [private]
is the representation of computed execution path.
It holds pair of function and dependency block from function through which is the execution `flowing`.
Definition at line 114 of file apex.h.
Referenced by findPath(), printPath(), and removeUnneededStuff().
protected_functions_
std::vector<std::string> APEXPass::protected_functions_ [private]
Initial value:
= {
            
            "_apex_exit",
            "_apex_extract_int",
            
            "llvm.stackrestore",
            "llvm.stacksave",
    }
Protected functions IDs. These will not be removed by APEXPass.
Definition at line 123 of file apex.h.
Referenced by collectProtectedFunctions(), and functionIsProtected().
The documentation for this class was generated from the following files:
apex.h
apex.cpp